Repository freifunk-berlin/firmware, pull requests merged in 2019-06, with the labels that each got.

#685 README: update reference of quilt to relevant page of OpenWrt-wiki
  README.md
Labels: bug

#627 build: add the new luci-app-opkg to all image types (luci-master)
  configs/common.config
  packages/backbone.txt
  packages/backbone_4MB.txt
  packages/default.txt
  packages/tunnel-berlin-openvpn.txt
  packages/tunnel-berlin-tunneldigger.txt
Labels: feed-luci

#693 Minify ipq44xx-config
  configs/ipq40xx-generic.config
Labels: bug

#663 improve building on Buildbot and friends
  Makefile
  configs/common-autobuild.config
  configs/common.config
Labels: buildsystem, enhancement
